# Generated by Django 5.0.1 on 2024-02-08 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followed_by_user_count",
            field=models.PositiveIntegerField(default=0, verbose_name="User follows"),
        ),
        migrations.AddField(
            model_name="user",
            name="have_followers_count",
            field=models.PositiveIntegerField(default=0, verbose_name="followers"),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(null=True, verbose_name="Post")),
                (
                    "likes_count",
                    models.PositiveIntegerField(default=0, verbose_name="likes"),
                ),
                ("dt", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_liked_this",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_liked_post",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User liked post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserNetwork",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
