# Generated by Django 5.0.1 on 2024-02-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_user_followed_by_user_count_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-dt"],
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(null=True, verbose_name="New Post"),
        ),
    ]
