# Generated by Django 5.0.1 on 2024-02-09 18:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_alter_post_options_post_title_alter_post_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
    ]
